LDSCRIPT .kernel
FLAGS _tmp-y.o += -D__KERNEL__

SRC y start.S
SRC y entry.S
SRC y assert.cc
SRC y gpio.cc
SRC y led.cc
SRC y exceptions.cc
SRC y irq.cc
DIR y memory
SRC y arch_info.cc
SRC y uart.cc
SRC y kprintf.cc
SRC y timer.cc
SRC y main.cc
SRC y list-test.cc
